sudo: required
language: C

services:
  - docker

cache:
    directories:
      - $HOME/.cache

stages:
  - test
  - name: deploy
    # Deploy packages to PackageCloud from tags and master
    # see:
    #   * https://github.com/tarantool/tarantool/issues/3745
    #   * https://github.com/travis-ci/travis-ci/issues/7780#issuecomment-302389370
    if: (branch = master OR tag IS present) AND (env(PACKAGECLOUD_TOKEN) IS present)

env:
  global:
    - PRODUCT=tarantool-queue

before_script:
  - git describe --long

_deploy_to_packagecloud: &deploy_to_packagecloud
  provider: packagecloud
  username: tarantool
  token: $PACKAGECLOUD_TOKEN
  dist: $OS/$DIST
  package_glob: build/*.{rpm,deb}
  skip_cleanup: true

# Pack and deploy packages to PackageCloud
_packpack: &packpack
  stage: deploy
  script:
    - git clone https://github.com/packpack/packpack.git
    - packpack/packpack
    - ls -l build/
  deploy:
    - <<: *deploy_to_packagecloud
      repository: "1_10"
    - <<: *deploy_to_packagecloud
      repository: "2x"
    - <<: *deploy_to_packagecloud
      repository: "2_2"

jobs:
  include:
    - env: VERSION=1_10
      script: ./test.sh
    - env: VERSION=2x
      script: ./test.sh
    - env: VERSION=2_2
      script: ./test.sh

    - <<: *packpack
      env: OS=el DIST=6
    - <<: *packpack
      env: OS=el DIST=7
    - <<: *packpack
      env: OS=fedora DIST=28
    - <<: *packpack
      env: OS=fedora DIST=29
    - <<: *packpack
      env: OS=fedora DIST=30
    - <<: *packpack
      env: OS=ubuntu DIST=trusty
    - <<: *packpack
      env: OS=ubuntu DIST=xenial
    - <<: *packpack
      env: OS=ubuntu DIST=bionic
    - <<: *packpack
      env: OS=ubuntu DIST=cosmic
    - <<: *packpack
      env: OS=ubuntu DIST=disco
    - <<: *packpack
      env: OS=debian DIST=jessie
    - <<: *packpack
      env: OS=debian DIST=stretch
    - <<: *packpack
      env: OS=debian DIST=buster

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
